/**
 * concatter
 * This function is used to merge multiple classes generated by the BEMClassManager
 * We will also remove double classes
 * @return {string}
 */
"use strict";

var _ = require('lodash');

function c() {

    this.classes = [];
    for( var i = 0; i < arguments.length; i++)
    {
        if(
            arguments[i] === undefined ||
            arguments[i] === null ||
            arguments[i] === "false"
        )
        continue;

        this.classes = this.classes.concat(arguments[i].toString().split(' '));
    }

    this.classes = _.uniq( this.classes );
    this.classes = _.without( this.classes, "false" );
    this.classes =  this.classes.join(' ');
}


module.exports = c;