/**
 * concatter
 * This function is used to merge multiple classes generated by the BEMClassManager
 * We will also remove double classes
 * @return {string}
 */
"use strict";

var _ = require('lodash');

function c() {
    classes = [];

    for( var i = 0; i < arguments.length; i++)
    {
        if(
            arguments[i] === undefined ||
            arguments[i] === null ||
            arguments[i] === "false"
        )
        continue;

        classes = classes.concat(arguments[i].toString().split(' '));
    }

    classes = _.uniq( classes );
    classes = _.without( classes, "false" );

    return classes.join(' ');
}

module.exports = c;